plugins { id 'com.android.application' }

android {
    namespace 'in.bharatdrop.app'
    compileSdk 35

    defaultConfig {
        applicationId 'in.bharatdrop.app'
        minSdk 26
        targetSdk 35
        versionCode 54
        versionName '5.4'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
